printWidth: 130
tabWidth: 4
useTabs: true
semi: false
singleQuote: true
quoteProps: 'consistent'
trailingComma: 'es5'
bracketSpacing: true
arrowParens: 'always'
insertPragma: false
proseWrap: 'never'
endOfLine: 'lf'
embeddedLanguageFormatting: 'off'
